services:
  # API 服务配置
  sam-app-api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    container_name: sam-app-api
    # 暴露 3000 端口到宿主机
    ports:
      - "13100:3100"
    # 依赖于 MySQL 服务，确保 MySQL 先启动
    depends_on:
      - sam-app-mysql
    # 连接到 sam-app-network 网络
    networks:
      - sam-app-network
    # 除非手动停止，否则容器会自动重启
    # restart: unless-stopped

  dev-sam-app-api:
    profiles:
      - dev
    volumes:
      - ../api:/app/api
      - ../shared:/app/shared
      - ../node_modules:/app/node_modules
    image: docker.m.daocloud.io/node:22-slim
    working_dir: /app/api
    command: node --watch dist/index.js
    container_name: dev-sam-app-api
    # 暴露 3000 端口到宿主机
    ports:
      - "13100:3100"
    # 依赖于 MySQL 服务，确保 MySQL 先启动
    depends_on:
      - sam-app-mysql
    # 连接到 sam-app-network 网络
    networks:
      - sam-app-network

  # MySQL 数据库服务
  sam-app-mysql:
    image: mysql:8.0
    container_name: sam-app-mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hotdogc1017
      - MYSQL_DATABASE=sam_app_db
    # 数据卷挂载，用于持久化 MySQL 数据和初始化脚本
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # 连接到 sam-app-network 网络
    networks:
      - sam-app-network
    # 除非手动停止，否则容器会自动重启
    restart: unless-stopped
    # MySQL 启动命令，设置默认认证插件
    command: --default-authentication-plugin=mysql_native_password

# 定义网络
networks:
  sam-app-network:
    name: sam-app # 指定网络名称为 sam-app

# 定义数据卷
volumes:
  mysql-data:
